### ISSUE TITLE
Update to vscode version 1.40 cann't  rebuild tags.

### ISSUE THREAD

**Issue by monian6251** [jaycetyle/vscode-gnu-global#14]

**Comment by monian6251** [comment]
version 1.39.2 is ok.

**Comment by jaycetyle** [comment]
Hi, could you please provide your OS enviroment and where you downloaded the GNU Global binary? If you use Windows, please let me know if you use WSL (Windows subsystem for linux) or not. Many thanks for your report!

**Comment by jaycetyle** [comment]
I found that there's some bugs in Nodejs on Windows. Please refered to the [nodejs#29008](https://github.com/nodejs/node/issues/29008). I also created [an issue to VSCode](https://github.com/microsoft/vscode/issues/84540). 

You can try to set "gnuGlobal.gtagsForceCpp" to "Enabled" for a workaround if you have the same issue on your system.

**Comment by monian6251** [comment]
windows 7 service pack 1
no WSL
GNU GLobal 6.6.3 http://adoxa.altervista.org/global/dl.php?f=win32

C/C++ GNU Global 0.3.1
vscode version 1.40 
run show gnu global version  OK
run rebuild gtags database  ERROR

**Comment by monian6251** [comment]
"gnuGlobal.gtagsForceCpp": "Enabled"
It works ,Thank you.
