### ISSUE TITLE
Support set encoding

### ISSUE THREAD

**Issue by LANB0** [jaycetyle/vscode-gnu-global#3]
Please add the encoding setting to Support Simplified Chinese on Windows

**Comment by jaycetyle** [comment]
Thanks for your report. I added this feature in v0.2.6. You can find a new configuration "gnuGlobal.encoding" to set the encoding of your enviroment. Please try it and let me know if it works for you or not.

**Comment by LANB0** [comment]
Thanks for the update,it works well.
